FORMAT: 1A

# QC ads API
This document describes QC ads API 

# Credentials
To use the API you need to obtain application credentials — ``APP_ID`` and ``APP_SECRET`` 

# Request

### URL
Base URL is `` https://{domain}/api/v1/ ``

### Required field
Every request must contain following fields:

* ``app_id`` — ``APP_ID`` credential
* ``sign`` — request sign
* ``rnd`` — random string

### How to calculate ``sign`` field with PHP
```
$sign = '';
ksort($params);
foreach ($params as $key => $value) {
    if ('sign' === $key) {
        continue;
    }
    $sign .= $key . '=' . $value;
}
$sign .= 'APP_SECRET';
$sign = sha1($sign);
```
