FORMAT: 1A

# QC Ads API
This document describes *QC Ads API* 

# Credentials
To use the API you need to obtain application credentials — ``APP_ID`` and ``APP_SECRET`` 

# Request

## URL
Base URL is `` https://{domain}/api/v1/ ``

## Required field
Every request must contain following fields:

|Field|Description|
|---|:--|
|``app_id``|``APP_ID`` credential|
|``sign``|Request sign|
|``rnd``|Random string|

## Sign calculating

How to calculate ``sign`` field with PHP:
```
$sign = '';
ksort($params);
foreach ($params as $key => $value) {
    if ('sign' === $key) {
        continue;
    }
    $sign .= $key . '=' . $value;
}
$sign .= 'APP_SECRET';
$sign = sha1($sign);
```

# Response

## Status Codes

We'll respond with one of the following status codes:

|Code|Description|
|---|:--|
|200|Success. Request completed.|
|201|Success. New resource created.|
|204|Success. No content to return. Only the status code returns.|
|400|Bad Request — The request could not be parsed.|
|401|Unauthorized — user is not logged in, cannot access resource.|
|404|Not Found — resource doesn't exist.|
|422|Unprocessable Entity — The request could not be parsed due to validation errors.|
|429|Rate limit exceeded, try again later.|
|500|Server error.|

## Envelope

All API responses will be returned in JSON format in one of following envelope:

### Success Response
```
{
    "success": true,
    "data": {
        "integer": 12345,
        "string": "John",
        "bool": true,
        "null": null,
        "array": [1,2,3],
        "object": {
            "one": 1,
            "two": 2,
            "three": 3
        }
    }
}
```

### Failed Response
```
{
    "success": false,
    "error": {
        "code": 42,
        "message": "Error message"
    }
}
```

## Error Codes

|Code|Description|
|---|:--|
|9000|Unknown error.|
|9001|Concrete error.|

# Limits

There are limits of requests per hour.

# Group Campaigns 
Campaigns-related resources of *QC Ads API*.

## Campaign [/campaign/{id}]
A single Campaign object.

+ Parameters
    + id (required, integer) ... ID of the Campaign

+ Model (application/json)


    + Body

            {
                "_links": {
                    "self": { "href": "/gists/42" },
                    "star": { "href": "/gists/42/star" },
                },
                "id": "42",
                "created_at": "2014-04-14T02:15:15Z",
                "description": "Description of Gist",
                "content": "String contents"
            }

### Retrieve a Single Campaign [GET]
+ Response 200

    [Campaign][]
